---
- name: Adiciona a chave do repo do Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adiciona o repo do k8s para o ubuntu
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Instala os pacotes do kubeadm, kubectl e kubelet
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet 
      - kubeadm 
      - kubectl

- name: Restart o daemon kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted