---
- hosts: master
  become: true
  become_user: root
  tasks:
    - name: Initialize the Kubernetes cluster using kubeadm
      command: "{{ item }}"
      with_items:
        - kubeadm config images pull  
        - kubeadm init

    - name: Create Directory and Conf file to kubeadm
      command: "{{ item }}"
      with_items:
        - mkdir -p $HOME/.kube
        - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
   
    - name: Copy the Manifest to install WaveNet
      copy:
        src: ./files/weave-daemonset.yaml
        dest: $HOME/
      
    - name: Install WaveNet pod network
      command: kubectl apply -f $HOME/weave-daemonset.yaml
    
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"